[package]
name = "Spychat"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = "0.53.2"
log = "0.4.20"
once_cell = "1.19.0"
pretty_env_logger = "0.5.0"
serde = "1.0.193"
serde_json = "1.0.108"
tokio = "1.35.1"
